apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: my-release
    namespace: default
spec:
    chart: 
        spec:
            chart: cockroachdb
            sourceRef: 
                kind: HelmRepository
                name: cockroachdb
            version: ">=10.0.0"
    interval: 1m0s
    values:
        egressRules:
            denyConnectionsToExternal: false